###
PUT http://localhost:5000/api/users/618ee200e9c289b4cf51b4a0/unfollow HTTP/1.1
Content-Type: "application/json"

{   
    "followingUser": {
        "userID":"618ee200e9c289b4cf51b4a0",
    },
    "currentUser": {
        "userID":"618ee1b5e9c289b4cf51b49d"
    },

}
###
GET http://localhost:5000/api/posts?page=1&limit=10
